### ISSUE TITLE
image doesn't contain a installed version of pimcore

### ISSUE THREAD

**Issue by timaschew** [pimcore/docker-pimcore-demo-standalone#3]
I get redirected to `http://192.168.99.101/install/` there is no admin site after a fresh setup.
I get a form to fill in MySQL setup, it's unclear what the MySQL username, password, and database should be.

here is the docker logfile

```
2016-01-22 11:11:43,992 CRIT Supervisor running as root (no user in config file)
2016-01-22 11:11:43,992 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-01-22 11:11:44,013 INFO RPC interface 'supervisor' initialized
2016-01-22 11:11:44,013 WARN cElementTree not installed, using slower XML parser for XML-RPC
2016-01-22 11:11:44,013 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-22 11:11:44,013 INFO supervisord started with pid 1
2016-01-22 11:11:45,017 INFO spawned: 'mysql' with pid 394
2016-01-22 11:11:45,019 INFO spawned: 'php-fpm' with pid 395
2016-01-22 11:11:45,020 INFO spawned: 'redis' with pid 396
2016-01-22 11:11:45,022 INFO spawned: 'apache2' with pid 397
2016-01-22 11:11:45,042 DEBG 'apache2' stderr output:
apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2 for ServerName

2016-01-22 11:11:45,042 DEBG fd 24 closed, stopped monitoring <POutputDispatcher at 33086280 for <Subprocess at 32581032 with name apache2 in state STARTING> (stderr)>
2016-01-22 11:11:45,063 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 33084840 for <Subprocess at 32581248 with name php-fpm in state STARTING> (stdout)>
2016-01-22 11:11:45,319 DEBG 'mysql' stderr output:
2016-01-22 11:11:45 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
2016-01-22 11:11:45 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-01-22 11:11:45 0 [Note] /usr/sbin/mysqld (mysqld 5.6.25-1~dotdeb+7.1) starting as process 406 ...

2016-01-22 11:11:46,320 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-22 11:11:46,321 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-22 11:11:46,321 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-22 11:11:46,321 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by timaschew** [comment]
somehow I get it working and now I get an error on the root site (not admin panel)

```
Zend_Controller_Router_Exception
HELP
No route, document, custom route or redirect is matching the request: / | Specific ERROR: No route matched the request
```

```
/var/www/pimcore/lib/Pimcore.php
            try {
                $front->dispatch();
            } catch (\Zend_Controller_Router_Exception $e) {
                if(!headers_sent()) {
                    header("HTTP/1.0 404 Not Found");
                }
                \Logger::err($e);
                throw new \Zend_Controller_Router_Exception("No route, document, custom route or redirect is matching the request: " . $_SERVER["REQUEST_URI"] . " | \n" . "Specific ERROR: " . $e->getMessage());
            } catch (\Exception $e) {
                if(!headers_sent()) {
```

```
GET Data empty
POST Data empty
Files empty
Cookies
pimcore_admin_sid	8j87qac0nsl187k1eebvqmpu55
Session empty
Server/Request Data
USER	www-data
HOME	/var/www
FCGI_ROLE	RESPONDER
REDIRECT_SCRIPT_URL	/
REDIRECT_SCRIPT_URI	http://192.168.99.101/
REDIRECT_HTTP_AUTHORIZATION	
REDIRECT_HANDLER	php5-fcgi
REDIRECT_STATUS	200
no_gzip	1
dont_vary	1
SCRIPT_URL	/
SCRIPT_URI	http://192.168.99.101/
HTTP_AUTHORIZATION	
HTTP_HOST	192.168.99.101
HTTP_CONNECTION	keep-alive
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_USER_AGENT	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
HTTP_ACCEPT_ENCODING	gzip, deflate, sdch
HTTP_ACCEPT_LANGUAGE	de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
HTTP_COOKIE	pimcore_admin_sid=8j87qac0nsl187k1eebvqmpu55
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_SIGNATURE	<address>Apache/2.2.22 (Debian) Server at 192.168.99.101 Port 80</address>
SERVER_SOFTWARE	Apache/2.2.22 (Debian)
SERVER_NAME	192.168.99.101
SERVER_ADDR	172.17.0.2
SERVER_PORT	80
REMOTE_ADDR	192.168.99.1
DOCUMENT_ROOT	/var/www/
SERVER_ADMIN	[no address given]
SCRIPT_FILENAME	/var/www/index.php
REMOTE_PORT	53434
REDIRECT_URL	/index.php
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.1
REQUEST_METHOD	GET
QUERY_STRING	
REQUEST_URI	/
SCRIPT_NAME	/index.php
ORIG_SCRIPT_FILENAME	/fcgi-php5-fpm
ORIG_PATH_INFO	/index.php
ORIG_PATH_TRANSLATED	/var/www/index.php
ORIG_SCRIPT_NAME	/php5-fcgi
PHP_SELF	/index.php
REQUEST_TIME_FLOAT	1453462028.2239
REQUEST_TIME	1453462028
TMPDIR	/var/www/website/var/cache
TEMP	/var/www/website/var/cache
TMP	/var/www/website/var/cache
windir	/var/www/website/var/cache
SystemRoot	/var/www/website/var/cache
Environment Variables
TMPDIR	/var/www/website/var/cache
TEMP	/var/www/website/var/cache
TMP	/var/www/website/var/cache
windir	/var/www/website/var/cache
SystemRoot	/var/www/website/var/cache
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
1. Whoops\Handler\JsonResponseHandler
```

**Comment by cleggypdc** [comment]
Maybe the run.sh file has not run correctly. perhaps mysql in your container took a while longer to start. This file basically imports the demo database for you so that you do not get prompted to setup pimcore.

Did you build manually or pull the image from Docker hub? If you know how to manually build, perhaps a quick change of a higher value in this line may fix it
https://github.com/pimcore/docker-pimcore-demo-standalone/blob/master/run.sh#L7

**Comment by timaschew** [comment]
I build the image by myself.

I destroyed my docker machine and did everything again, same result. 
There is an error in the `run.sh` script, please fix it.

```
sudo -u www-data mv /var/www/website/var/config/system.xml.template /var/www/website/var/config/system.xml

mv: cannot stat `/var/www/website/var/config/system.xml.template': No such file or directory
```

**Comment by timaschew** [comment]
same issue if I use the image from the docker hub

This is the log after extracting the zip file
```
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
mv: cannot stat `/var/www/website/var/config/system.xml.template': No such file or directory
2016-01-23 16:11:32,466 CRIT Supervisor running as root (no user in config file)
2016-01-23 16:11:32,466 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-01-23 16:11:32,554 INFO RPC interface 'supervisor' initialized
2016-01-23 16:11:32,554 WARN cElementTree not installed, using slower XML parser for XML-RPC
2016-01-23 16:11:32,554 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-23 16:11:32,556 INFO supervisord started with pid 1
2016-01-23 16:11:33,559 INFO spawned: 'mysql' with pid 396
2016-01-23 16:11:33,562 INFO spawned: 'php-fpm' with pid 397
2016-01-23 16:11:33,564 INFO spawned: 'redis' with pid 398
2016-01-23 16:11:33,570 INFO spawned: 'apache2' with pid 399
2016-01-23 16:11:33,641 DEBG 'apache2' stderr output:
apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2 for ServerName

2016-01-23 16:11:33,642 DEBG fd 24 closed, stopped monitoring <POutputDispatcher at 18746184 for <Subprocess at 18240936 with name apache2 in state STARTING> (stderr)>
2016-01-23 16:11:33,805 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 18744744 for <Subprocess at 18241152 with name php-fpm in state STARTING> (stdout)>
2016-01-23 16:11:34,057 DEBG 'mysql' stderr output:
2016-01-23 16:11:34 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
2016-01-23 16:11:34 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-01-23 16:11:34 0 [Note] /usr/sbin/mysqld (mysqld 5.6.25-1~dotdeb+7.1) starting as process 400 ...

2016-01-23 16:11:35,061 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-23 16:11:35,062 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-23 16:11:35,062 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-23 16:11:35,062 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by timaschew** [comment]
If I try to run the install process with the credentials from the run.sh by my own
I get this error 

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails' in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array) #2 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #3 /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('\n\nDROP TABLE IF...', Array) #4 [internal function]: Zend_Db_Adapter_Pdo_Abstract->query('\n\nDROP TABLE IF...') #5 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(260): call_user_func_array(Array, Array) #6 /var/www/pimcore/lib/Pimcore/Db/Wrapper.php(230): Pimco in /var/www/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
```

**Comment by cleggypdc** [comment]
Actually this may be due to the most recent commits to the pimcore GitHub that have removed system.xml etc and replaced them with JSON equivalent. I'm pretty sure that the demo build uses the latest build.
It might be worth just checking this on the Google groups to confirm :-)






On Sat, Jan 23, 2016 at 7:38 AM -0800, "Anton Wilhelm" <notifications@github.com> wrote:












I build the image by myself.



I destroyed my docker machine and did everything again, same result. 

There is an error in the run.sh script, please fix it.

sudo -u www-data mv /var/www/website/var/config/system.xml.template /var/www/website/var/config/system.xml

mv: cannot stat `/var/www/website/var/config/system.xml.template': No such file or directory

**Comment by brusch** [comment]
Yes, thats true, ... all the configs are now stored in PHP configuration files: 
https://github.com/pimcore/pimcore/tree/master/website_demo/var/config

The docker image is based on the latest build, so the Dockerfile needs some modifications to run with it. I'll try to fix that as soon as possible.

**Comment by timaschew** [comment]
Which version of pimcore is working with the docker image, which git hash of pimcore/pimcore, so that I can install that version instead of the master.

**Comment by brusch** [comment]
Just made some modifications which should fix the problem. 
You can try it again as soon as the builds are ready: https://hub.docker.com/r/pimcore/docker-pimcore-demo-standalone/builds/
